when:
  - event:
      - push

steps:
  - name: build
    image: zmkfirmware/zmk-build-arm:stable@sha256:0979a8de325e3d822e48bd8d1d9efaee2984ad3750253119f920a342f0ce5cde
    commands:
      - mkdir config
      - mv west.yml boards config/
      - west init -l config
      - west update
      - west zephyr-export
      - west list
      # build Zaphod - outputs build/zaphod/zephyr/zmk.uf2
      - west build -s zmk/app -b zaphod -d build/zaphod -- -DZMK_CONFIG="$CI_WORKSPACE/config"
      # build Zaphod Lite w/ Seeduino XIAO - outputs  build/zaphod_lite_xiao/zephyr/zmk.uf2
      # - west build -s zmk/app -b seeeduino_xiao -d build/zaphod_lite_xiao -- -DZMK_CONFIG="$CI_WORKSPACE/config" -DSHIELD=zaphod_lite
      # build Zaphod Lite w/ Seeduino XIAO BLE - outputs build/zaphod_lite_xiao_ble/zephyr/zmk.uf2
      # - west build -s zmk/app -b seeeduino_xiao_ble -d build/zaphod_lite_xiao_ble -- -DZMK_CONFIG="$CI_WORKSPACE/config" -DSHIELD=zaphod_lite
      - cat -n build/zaphod/zephyr/.config
  - name: upload
    image: alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d
    commands:
      - apk add curl
      - stat build/zaphod/zephyr/zmk.uf2
      - |
        curl -sSf --user chdorner:$FORGEJO_TOKEN_CHDORNER_PACKAGE_WRITE \
          --upload-file build/zaphod/zephyr/zmk.uf2 \
          https://git.chdorner.com/api/packages/chdorner/generic/panic34/${CI_COMMIT_SHA}/zaphod.uf2 \
          && echo "created package version ${CI_COMMIT_SHA}"
      - |
        curl -sS --user chdorner:$FORGEJO_TOKEN_CHDORNER_PACKAGE_WRITE -X DELETE \
          "https://git.chdorner.com/api/packages/chdorner/generic/panic34/latest"
      - |
        curl -sSf --user chdorner:$FORGEJO_TOKEN_CHDORNER_PACKAGE_WRITE \
          --upload-file build/zaphod/zephyr/zmk.uf2 \
          https://git.chdorner.com/api/packages/chdorner/generic/panic34/latest/zaphod.uf2 \
          && echo "created package version latest"
    secrets:
      - FORGEJO_TOKEN_CHDORNER_PACKAGE_WRITE
    when:
      event: push
      branch: main
